---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-install-leapp"
      label: "Install Leapp"
      solveButton: false
    - name: "02-preupgrade-assistant"
      label: "Preupgrade Assistant"
      solveButton: false
    - name: "03-fixing-inhibitor"
      label: "Fixing Inhibitor"
      solveButton: false
    - name: "04-upgrading"
      label: "Upgrading"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_host/ssh/root
